name: CI

on:
  push:
    branches: ~

  pull_request: ~

  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PATH: ./app1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ${{ env.APP_PATH }}/yarn.lock

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.APP_PATH }}

      - name: Build with Vite
        run: yarn build
        working-directory: ${{ env.APP_PATH }}
