name: CI

on:
  push:
    branches: ~

  pull_request: ~

  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        working-directory: ./app2

      - name: Build with Vite
        run: yarn build
        working-directory: ./app2
